### ISSUE TITLE
Question about creating groups

### ISSUE THREAD

**Issue by jmcclenny-epoc** [cannatag/ldap3#701]
I am having a hard time trying to figure out how to create security groups with this module. I tried to reference an LDIFDE to populate the objectClass and attributes, but I'm not getting good feedback if there is an issue.

Example: LDIFDE
```yml
changetype: add
objectClass: top
objectClass: group
cn: test.group
name: test.group
sAMAccountName: test.group
groupType: -2147483640
```

Code:
```python
groupdn = "<redacted>"

objectClass = ['group','top']
attr = {
  'cn': 'test.group',
  'name': 'test.group',
  'sAMAccountName': 'test.group',
  'groupType': '-2147483640'
}

c.add(groupdn , objectClass , attr)
```

Is there an example out there that I could review to create a group in Active Directory?
